language: generic
git:
  submodules: false
  depth: 1
services:
  - docker
os:
  - linux
  - osx
dist: bionic
env:
  matrix:
    - debug=true
    # - debug=""
install:
  - "./tests/CI/install-deps-and-mdm.sh"
script:
  - "./tests/CI/non-docker-menu-selections.sh"
  - "./tests/CI/docker-menu-selections.sh"
  - "./tests/CI/create-detached-mdm.sh"
  - "./tests/CI/create-mdm-app-from-mc-repo.sh"
  - "./tests/CI/check-homebrew.sh"
