language: generic
git:
  submodules: false
  depth: 1
services:
  - docker
os:
  - linux
  - osx
dist: bionic
env:
  - debug=true
  - debug=""

install:
  - "./tests/CI/install-deps-and-mdm.sh"
script:
  - "./tests/CI/non-docker-menu-selections.sh"
  - "./tests/CI/end-to-end-PWA.sh"

jobs:
  include:
    - stage: post-not-mac
      if: os != osx
      script:
        - "./tests/CI/docker-menu-selections.sh"
    - stage: post-mac
      if: os == osx
      after_script:
        - "./tests/CI/check-homebrew.sh"
