language: generic
script: ./tests/travis/install-deps-and-mdm.sh

git:
  submodules: false
  depth: 1

services:
  - docker

jobs:
  include:
    - os: osx
      osx_image: xcode11.5
    - dist: bionic