version: '3.0'
services:
  certbot-dns:
    image: pmetpublic/certbot-dns
    volumes:
      - "./certbot-dns/.dns-config.ini:/.dns-config.ini"
      - "${dest_dir:-.}:/etc/letsencrypt/archive"
    command: "
      --dns-digitalocean \
      --dns-digitalocean-credentials /.dns-config.ini \
      --dns-digitalocean-propagation-seconds 30 \
      -d '${domain:-*.test.com}' "
  storystore-pwa:
    image: pmetpublic/storystore-pwa:docker
    environment:
      - MAGENTO_URL=${MAGENTO_URL:-https://venia.magento.com/graphql}
      - NEXT_TELEMETRY_DISABLED=1
      - CLOUD_MODE=${CLOUD_MODE:-false}
      - PREV_RELEASE_REDIRECT_URL=https://pwa-prev.the1umastory.com
      - LATEST_RELEASE_REDIRECT_URL=https://pwa.the1umastory.com
  storystore-pwa-prev:
    image: pmetpublic/storystore-pwa:docker-prev
    environment:
      - MAGENTO_URL=${MAGENTO_URL:-https://venia.magento.com/graphql}
      - NEXT_TELEMETRY_DISABLED=1
      - CLOUD_MODE=${CLOUD_MODE:-false}
      - PREV_RELEASE_REDIRECT_URL=https://pwa-prev.the1umastory.com
      - LATEST_RELEASE_REDIRECT_URL=https://pwa.the1umastory.com

