version: '3.0'
services:
  cert-generator:
    image: pmetpublic/certbot-dns
    volumes:
      - ".dns-config.ini:/.dns-config.ini"
      - "/dest/path/archive:/etc/letsencrypt/archive"
    command: '
      --dns-digitalocean \
      --dns-digitalocean-credentials /.dns-config.ini \
      --dns-digitalocean-propagation-seconds 30 \
      -d "*.yourdomain.com" '
  nginx-rev-proxy-setup:
    command: /tmp/nginx-rev-proxy-setup.sh
    image: debian:stable-slim
    environment: 
      - cert_dir="$mdm_cert_dir"
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ../bin/nginx-rev-proxy-setup.sh:/tmp/nginx-rev-proxy-setup.sh:ro
