version: '3.0'
services:
  cert-generator:
    image: pmetpublic/certbot-dns
    volumes:
      - ".dns-config.ini:/.dns-config.ini"
      - "/dest/path/archive:/etc/letsencrypt/archive"
    command: '
      --dns-digitalocean \
      --dns-digitalocean-credentials /.dns-config.ini \
      --dns-digitalocean-propagation-seconds 30 \
      -d "*.yourdomain.com" '
