version: '3.0'
services:
  cert-generator:
    image: pmetpublic/certbot-dns
    volumes:
      - "./certbot-dns/.dns-config.ini:/.dns-config.ini"
      - "/dest/path/archive:/etc/letsencrypt/archive"
    command: '
      --dns-digitalocean \
      --dns-digitalocean-credentials /.dns-config.ini \
      --dns-digitalocean-propagation-seconds 30 \
      -d "*.yourdomain.com" '
  storystore-pwa:
    image: pmetpublic/storystore-pwa:latest
    environment:
      - MAGENTO_URL=${MAGENTO_URL:-https://venia.magento.com/graphql}
      - NEXT_TELEMETRY_DISABLED=1
      - DEMO_MODE=${DEMO_MODE:-false}
    ports:
      - 3000:3000
  storystore-pwa:
    image: pmetpublic/storystore-pwa:prev
    environment:
      - MAGENTO_URL=${MAGENTO_URL:-https://venia.magento.com/graphql}
      - NEXT_TELEMETRY_DISABLED=1
      - DEMO_MODE=${DEMO_MODE:-false}
    ports:
      - 3001:3000
