services:
  # this should only exist if .magento.env.yaml exists and then values should be translated
  db:
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    networks:
      default:
        aliases:
          - database.internal
  varnish:
    ports:
      - 80
  build:
    environment:
      - COMPOSER_HOME=/app/.composer
      - COMPOSER_AUTH
  deploy:
    environment:
      - COMPOSER_AUTH
  opensearch:
    image: 'opensearchproject/opensearch:1.2.4'
    command: 'bash -c "bin/opensearch-plugin install -b analysis-icu || :;
      bin/opensearch-plugin install -b analysis-icu || :;
      ./opensearch-docker-entrypoint.sh"'
    networks:
      default:
        aliases:
          - opensearch.internal
    # extending generic to disable healthcheck did not work. docker-compose issue?
    healthcheck:
      disable: true
  web:
    ports:
      - 80
    environment:
      - NGINX_WORKER_PROCESSES=auto
  fpm:
    # extending generic to disable healthcheck did not work. docker-compose issue?
    healthcheck:
      disable: true