version: '2.1'
services:
  # this should only exist if .magento.env.yaml exists and then values should be translated
  db:
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    networks:
      default:
        aliases:
          - database.internal
  varnish:
    ports:
      - 80
  build:
    environment:
      - COMPOSER_HOME=/app/.composer
      - COMPOSER_AUTH
  deploy:
    environment:
      - COMPOSER_AUTH
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      default:
        aliases:
          - elasticsearch.internal
    # extending generic to disable healthcheck did not work. docker-compsoe issue?
    healthcheck:
      disable: true
  web:
    ports:
      - 80
  fpm:
    # extending generic to disable healthcheck did not work. docker-compsoe issue?
    healthcheck:
      disable: true