version: '2.1'
services:
  # this should only exist if .magento.env.yaml exists and then values should be translated
  db:
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    networks:
      default:
        aliases:
          - database.internal
  varnish:
    ports:
      - 80
  build:
    environment:
      - COMPOSER_HOME=/app/.composer
      - COMPOSER_AUTH
  deploy:
    environment:
      - COMPOSER_AUTH
  elasticsearch:
    networks:
      default:
        aliases:
          - elasticsearch.internal
  web:
    ports:
      - 80
