version: '2.1'
services:
  db:
    labels: 
      - com.magento.dockerized
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    networks:
      default:
        aliases:
          - database.internal
  build:
    image: 'pmetpublic/magento-cloud-docker-php:7.3-cli-1.1'
    environment:
      - COMPOSER_HOME=/app/.composer
    command: cloud-build
  deploy:
    image: 'pmetpublic/magento-cloud-docker-php:7.3-cli-1.1'
    command: cloud-deploy
    volumes:
      - 'magento:/app:rw'
      - 'magento-vendor:/app/vendor:rw'
      - 'magento-generated:/app/generated:rw'
  varnish:
    ports:
      - 80
    depends_on:
      web:
        condition: service_started
  elasticsearch:
    networks:
      default:
        aliases:
          - elasticsearch.internal
  web:
    image: 'pmetpublic/magento-cloud-docker-nginx'
