version: '2.1'
services:
  # start db
  # this should only exist if .magento.env.yaml exists and then values should be translated
  db:
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    networks:
      default:
        aliases:
          - database.internal
  ## end db
  build:
    image: $php_cli_docker_image
    environment:
      - COMPOSER_HOME=/app/.composer
    command: cloud-build
  deploy:
    image: $php_cli_docker_image
    command: cloud-deploy
    volumes:
      - 'magento:/app:rw'
      - 'magento-vendor:/app/vendor:rw'
      - 'magento-generated:/app/generated:rw'
    environment:
      - COMPOSER_AUTH
  varnish:
    ports:
      - 80
    depends_on:
      web:
        condition: service_started
  elasticsearch:
    networks:
      default:
        aliases:
          - elasticsearch.internal
  web:
    image: 'pmetpublic/magento-cloud-docker-nginx'
