name: create and lan

on:
  push:

jobs:
  dockerize-standalone:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        brew install platypus
        ./bin/dockerize -s