name: create and lan

on:
  push:

jobs:
  dockerize-standalone:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: create standalone mdm
        run: |
          brew install platypus
          ./bin/dockerize -s