name: test runner

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}

jobs:

  dockerize-then-run-detached-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: bats tests
        run: |
          ./tests/libs/bats/bin/bats -T -r ./tests/dockerize-then-run-detached-app
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master


  dockerize-then-run-magento-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: bats tests
        run: |
          ./tests/libs/bats/bin/bats -T -r ./tests/dockerize-then-run-magento-app/**/*.bats
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master

  generic-lib-and-non-app-specific:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: bats tests
        run: |
          ./tests/libs/bats/bin/bats -T -r ./tests/generic-lib-and-non-app-specific/**/*.bats
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master