name: test runner

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        # value: [true, ""]
        value: [true]
    env:
      debug: ${{ matrix.value }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: bats tests
        run: |
          ./tests/bats/**/*.bats
      - name: keepalive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
