name: test runner

on:
  push:
    branches:
      - master
      - develop
      - feature*

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
  MDM_CONFIG_URL: ${{ secrets.MDM_CONFIG_URL }}

jobs:

  # dockerize-then-run-detached-app:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #       MDM_OVERRIDE_CONFIG: [true, ""]
  #   env:
  #     MDM_OVERRIDE_CONFIG: ${{ matrix.MDM_OVERRIDE_CONFIG }}
  #   steps:
  #     - run: |
  #         if [[ "$MDM_OVERRIDE_CONFIG" ]]; then echo "::set-env name=MDM_CONFIG_URL::"; fi
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: 'true'
  #     - name: bats tests
  #       run: |
  #         ./tests/libs/bats/bin/bats -T -r ./tests/2-dockerize-then-run-detached-app
  #     - name: keep alive to debug
  #       if: ${{ failure() }}
  #       uses: PMET-public/action-tmate@master


  dockerize-then-run-magento-apps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        MDM_OVERRIDE_CONFIG: [""]
    env:
      MDM_OVERRIDE_CONFIG: ${{ matrix.MDM_OVERRIDE_CONFIG }}
    steps:
      - run: |
          if [[ "$MDM_OVERRIDE_CONFIG" ]]; then echo "::set-env name=MDM_CONFIG_URL::"; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: bats tests
        run: |
          # install the master and a 2nd to test simultaneous compatibility
          ./tests/libs/bats/bin/bats -T ./tests/3-dockerize-then-run-magento-app/all/1-install-mdm-and-create-magento-app.bats
          ./tests/libs/bats/bin/bats -T ./tests/3-dockerize-then-run-magento-app/all/installed-magento-app-lib.bats
      - name: bats tests for 2nd app
        run: |
          export MAGENTO_CLOUD_REF_TO_TEST=pmet-2.4.0-ref
          ./tests/libs/bats/bin/bats -T -r ./tests/3-dockerize-then-run-magento-app/**/*.bats
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master

  # generic-lib-and-non-app-specific:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #       MDM_OVERRIDE_CONFIG: [true, ""]
  #   env:
  #     MDM_OVERRIDE_CONFIG: ${{ matrix.MDM_OVERRIDE_CONFIG }}
  #   steps:
  #     - run: |
  #         if [[ "$MDM_OVERRIDE_CONFIG" ]]; then echo "::set-env name=MDM_CONFIG_URL::"; fi
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: 'true'
  #     - name: bats tests
  #       run: |
  #         ./tests/libs/bats/bin/bats -T -r ./tests/1-generic-lib-and-non-app-specific/**/*.bats
  #     - name: keep alive to debug
  #       if: ${{ failure() }}
  #       uses: PMET-public/action-tmate@master