name: test runner

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        # value: [true, ""]
        value: [true]
    env:
      debug: ${{ matrix.value }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: checkout
        run: |
          ./tests/bats/01-checkout.bats
      - name: install
        run: |
          ./tests/bats/02-install.bats
      - name: install
        run: |
          ./tests/bats/03-post-install.bats
      - name: non-docker tests
        run: |
          ./tests/CI/non-docker-menu-selections.sh
      - name: docker tests
        run: |
          ./tests/CI/docker-menu-selections.sh
      - name: create detached mdm
        run: |
          ./tests/CI/create-detached-mdm.sh
      - name: create mdm app from mc repo
        run: |
          ./tests/CI/create-mdm-app-from-mc-repo.sh
      - name: check homebrew dependency behavior
        run: |
          ./tests/CI/check-homebrew.sh
      - name: keepalive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
