name: test runner

on:
  push:

jobs:
  dockerize-standalone:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: create standalone mdm
        run: |
          ./tests/CI/install-deps-and-mdm.sh